package docsgen_test

import (
	"strings"
	"testing"

	"go.flow.arcalot.io/docsgen"
)

func TestGenerate_missingPlaceholder(t *testing.T) {
	_, err := docsgen.Generate([]byte(""), emptyTestSchema)
	if err == nil {
		t.Fatalf("Generate with no placeholder should result in an error.")
	}
}

func TestGenerate_emptySchema(t *testing.T) {
	result, err := docsgen.Generate([]byte(
		"<!-- Autogenerated documentation by arcaflow-docsgen --><!-- End of autogenerated documentation -->"),
		emptyTestSchema,
	)
	if err != nil {
		t.Fatalf("Generate with an empty schema should not result in an error.")
	}
	if !strings.Contains(string(result), "<!-- Autogenerated documentation by arcaflow-docsgen -->") {
		t.Fatalf("The result does not contain the placeholder.")
	}
	if !strings.Contains(string(result), "<!-- End of autogenerated documentation -->") {
		t.Fatalf("The result does not contain the placeholder.")
	}
	if len(result) <= len("<!-- Autogenerated documentation by arcaflow-docsgen --><!-- End of autogenerated documentation -->") {
		t.Fatalf("The result does not contain any content.")
	}
}
